import { build as esbuild } from "esbuild";
import { build as viteBuild } from "vite";
import { rm, readFile, writeFile, mkdir } from "node:fs/promises";

// server deps to bundle to reduce openat(2) syscalls
// which helps cold start times
const allowlist = [
  "@google/generative-ai",
  "axios",
  "cors",
  "date-fns",
  "drizzle-orm",
  "drizzle-zod",
  "express",
  "express-rate-limit",
  "express-session",
  "jsonwebtoken",
  "memorystore",
  "multer",
  "nanoid",
  "nodemailer",
  "openai",
  "passport",
  "passport-local",
  "postgres",
  "stripe",
  "uuid",
  "ws",
  "xlsx",
  "zod",
  "zod-validation-error",
];

async function buildAll() {
  await rm("dist", { recursive: true, force: true });

  console.log("building client...");
  await viteBuild();

  // Inline dist/public/index.html into the server bundle.
  // On Vercel the serverless function runs from /var/task/ with no
  // access to dist/public/ at runtime — server-side SEO injection
  // (server/main-host-spa.ts, server/microsite-spa.ts) needs the HTML
  // string to rewrite the <head>. Bundling it as a TS constant means
  // a single readFileSync at startup and no runtime filesystem lookup.
  const indexHtml = await readFile("dist/public/index.html", "utf-8");
  await mkdir("server/generated", { recursive: true });
  await writeFile(
    "server/generated/index-html.ts",
    `// AUTO-GENERATED by script/build.ts — do not edit by hand.\n// Bundled from dist/public/index.html so the Vercel serverless\n// function can inject SEO into the SPA <head> without a runtime\n// filesystem read.\nexport const BUNDLED_INDEX_HTML: string = ${JSON.stringify(indexHtml)};\n`,
    "utf-8",
  );

  console.log("building server...");
  const pkg = JSON.parse(await readFile("package.json", "utf-8"));
  const allDeps = [
    ...Object.keys(pkg.dependencies || {}),
    ...Object.keys(pkg.devDependencies || {}),
  ];
  const externals = allDeps.filter((dep) => !allowlist.includes(dep));

  await esbuild({
    entryPoints: ["server/index.ts"],
    platform: "node",
    bundle: true,
    format: "cjs",
    outfile: "dist/index.cjs",
    define: {
      "process.env.NODE_ENV": '"production"',
    },
    minify: true,
    external: externals,
    logLevel: "info",
  });

  console.log("building Vercel api handler...");
  await esbuild({
    entryPoints: ["server/vercel-entry.ts"],
    platform: "node",
    bundle: true,
    format: "cjs",
    target: "node20",
    outfile: "api/index.js",
    define: {
      "process.env.NODE_ENV": '"production"',
    },
    minify: true,
    external: externals,
    logLevel: "info",
  });
}

buildAll().catch((err) => {
  console.error(err);
  process.exit(1);
});
