import { build as esbuild } from "esbuild";
import { build as viteBuild } from "vite";
import { rm, readFile, writeFile, mkdir } from "node:fs/promises";

// server deps to bundle to reduce openat(2) syscalls
// which helps cold start times
const allowlist = [
  "@google/generative-ai",
  "axios",
  "cors",
  "date-fns",
  "drizzle-orm",
  "drizzle-zod",
  "express",
  "express-rate-limit",
  "express-session",
  "jsonwebtoken",
  "memorystore",
  "multer",
  "nanoid",
  "nodemailer",
  "openai",
  "passport",
  "passport-local",
  "postgres",
  "stripe",
  "svix",
  "uuid",
  "ws",
  "xlsx",
  "zod",
  "zod-validation-error",
];

async function buildAll() {
  await rm("dist", { recursive: true, force: true });

  console.log("building client...");
  await viteBuild();

  // Inline dist/public/index.html into the server bundle.
  // On Vercel the serverless function runs from /var/task/ with no
  // access to dist/public/ at runtime — server-side SEO injection
  // (server/main-host-spa.ts, server/microsite-spa.ts) needs the HTML
  // string to rewrite the <head>. Bundling it as a TS constant means
  // a single readFileSync at startup and no runtime filesystem lookup.
  const indexHtml = await readFile("dist/public/index.html", "utf-8");
  await mkdir("server/generated", { recursive: true });
  await writeFile(
    "server/generated/index-html.ts",
    `// AUTO-GENERATED by script/build.ts — do not edit by hand.\n// Bundled from dist/public/index.html so the Vercel serverless\n// function can inject SEO into the SPA <head> without a runtime\n// filesystem read.\nexport const BUNDLED_INDEX_HTML: string = ${JSON.stringify(indexHtml)};\n`,
    "utf-8",
  );

  console.log("building server...");
  const pkg = JSON.parse(await readFile("package.json", "utf-8"));
  const allDeps = [
    ...Object.keys(pkg.dependencies || {}),
    ...Object.keys(pkg.devDependencies || {}),
  ];
  const externals = allDeps.filter((dep) => !allowlist.includes(dep));

  await esbuild({
    entryPoints: ["server/index.ts"],
    platform: "node",
    bundle: true,
    format: "cjs",
    outfile: "dist/index.cjs",
    define: {
      "process.env.NODE_ENV": '"production"',
    },
    minify: true,
    external: externals,
    logLevel: "info",
  });

  console.log("building Vercel api handler...");
  await esbuild({
    entryPoints: ["server/vercel-entry.ts"],
    platform: "node",
    bundle: true,
    format: "cjs",
    target: "node20",
    outfile: "api/index.js",
    define: {
      "process.env.NODE_ENV": '"production"',
    },
    minify: true,
    external: externals,
    logLevel: "info",
  });

  // PR-#19-G: bundle the /api/og function ourselves rather than relying
  // on Vercel's native TSX function auto-build.
  //
  // Why: when we ship api/og.tsx as a source TSX file and let Vercel's
  // platform-side TSX builder handle it, we hit FUNCTION_INVOCATION_FAILED
  // at runtime (cold-start crash). Vercel's auto-build for non-framework
  // TSX functions produces a tiny lambda that imports `@vercel/og` at
  // runtime, but with our buildCommand + outputDirectory overrides it
  // doesn't reliably resolve the workspace's `../shared/` imports or
  // even the `@vercel/og` dependency from node_modules. Bundling here
  // ESM-style with `@vercel/og` external (and node_modules uploaded
  // alongside the lambda) gives us a deterministic, self-contained
  // entrypoint.
  // Source lives at src/og.tsx (NOT api/og.tsx) so that the .tsx
  // source and the bundled .js output don't collide as two routes
  // both wanting to be /api/og — Vercel rejects that with
  // `conflicting_file_path`. By keeping the source outside api/ we
  // get a clean one-route-per-output mapping.
  console.log("building /api/og function...");
  await esbuild({
    entryPoints: ["src/og.tsx"],
    platform: "node",
    bundle: true,
    // CJS, not ESM. Vercel's Node lambda runtime compiles ESM files
    // to CommonJS on deploy ("Compiling 'og.js' from ESM to
    // CommonJS..." in the build log) and that transform breaks our
    // createRequire/import.meta.url shim, leaving the lambda crashing
    // at boot with FUNCTION_INVOCATION_FAILED. Outputting CJS
    // directly skips the conversion step and gives Node a file it
    // can require() unchanged. Same format we use for api/index.js.
    format: "cjs",
    target: "node20",
    outfile: "api/og.js",
    jsx: "automatic",
    define: {
      "process.env.NODE_ENV": '"production"',
    },
    // @vercel/og pulls in WASM (yoga.wasm, resvg.wasm) and a font
    // asset via runtime path resolution against import.meta.url, so
    // it MUST stay external — node_modules is uploaded alongside the
    // lambda by Vercel's Node runtime.
    external: ["@vercel/og"],
    // Vercel's classic Node serverless function runtime expects
    // `module.exports` to BE the request handler `(req, res) => void`,
    // not an object of named exports. esbuild's CJS output puts our
    // handler at `module.exports.default`, which makes Vercel return
    // 405 Method Not Allowed for every request. This footer rebinds
    // module.exports to the default-export handler while preserving
    // the named GET export as a property for callers that might want
    // the Web-API form (e.g. local tests).
    footer: {
      js: "if (module.exports && typeof module.exports.default === 'function') { var __og_named = module.exports; module.exports = module.exports.default; module.exports.GET = __og_named.GET; }",
    },
    logLevel: "info",
  });
}

buildAll().catch((err) => {
  console.error(err);
  process.exit(1);
});
